/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author tigor
 */
public class viewEstoque extends javax.swing.JFrame {

    /**
     * Creates new form viewEstoque
     */
    public viewEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLacome = new javax.swing.JToggleButton();
        btnMilion = new javax.swing.JToggleButton();
        btnKenzo = new javax.swing.JToggleButton();
        btnLaVie = new javax.swing.JToggleButton();
        btnJadore = new javax.swing.JToggleButton();
        btnCoco = new javax.swing.JToggleButton();
        btnLight = new javax.swing.JToggleButton();
        btnCarolina = new javax.swing.JToggleButton();
        btnDolce = new javax.swing.JToggleButton();
        btnDior = new javax.swing.JToggleButton();
        btnLacomeComprar = new javax.swing.JButton();
        btnMilionComprar = new javax.swing.JButton();
        btnKenzoComprar = new javax.swing.JButton();
        btnLavieComprar = new javax.swing.JButton();
        btnJadoreComprar = new javax.swing.JButton();
        btnCocoComprar = new javax.swing.JButton();
        btnDolceComprar = new javax.swing.JButton();
        btnLightComprar = new javax.swing.JButton();
        btnDiorComprar = new javax.swing.JButton();
        btnJCarolinaComprar = new javax.swing.JButton();
        spiLacome = new javax.swing.JSpinner();
        spiDior = new javax.swing.JSpinner();
        spiKenzo = new javax.swing.JSpinner();
        spiLavie = new javax.swing.JSpinner();
        spiMilion = new javax.swing.JSpinner();
        spiCoco = new javax.swing.JSpinner();
        spiJadore = new javax.swing.JSpinner();
        spiDolce = new javax.swing.JSpinner();
        spiLight = new javax.swing.JSpinner();
        spiCarolina = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(219, 182, 238));

        btnLacome.setText("Lancôme");
        btnLacome.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                btnLacomeComponentAdded(evt);
            }
        });
        btnLacome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLacomeActionPerformed(evt);
            }
        });

        btnMilion.setText("1 Milion");
        btnMilion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMilionActionPerformed(evt);
            }
        });

        btnKenzo.setText("Kenzo");

        btnLaVie.setText("La Vie Est Belle");

        btnJadore.setText("j’adore, dior");

        btnCoco.setText("coco mademoiselle");

        btnLight.setText("light blue");

        btnCarolina.setText("carolina herrera");

        btnDolce.setText("dolce & gabbana");
        btnDolce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDolceActionPerformed(evt);
            }
        });

        btnDior.setText("Dior");
        btnDior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiorActionPerformed(evt);
            }
        });

        btnLacomeComprar.setText("Comprar");
        btnLacomeComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLacomeComprarActionPerformed(evt);
            }
        });

        btnMilionComprar.setText("Comprar");
        btnMilionComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMilionComprarActionPerformed(evt);
            }
        });

        btnKenzoComprar.setText("Comprar");
        btnKenzoComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKenzoComprarActionPerformed(evt);
            }
        });

        btnLavieComprar.setText("Comprar");
        btnLavieComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLavieComprarActionPerformed(evt);
            }
        });

        btnJadoreComprar.setText("Comprar");
        btnJadoreComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadoreComprarActionPerformed(evt);
            }
        });

        btnCocoComprar.setText("Comprar");
        btnCocoComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocoComprarActionPerformed(evt);
            }
        });

        btnDolceComprar.setText("Comprar");
        btnDolceComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDolceComprarActionPerformed(evt);
            }
        });

        btnLightComprar.setText("Comprar");
        btnLightComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLightComprarActionPerformed(evt);
            }
        });

        btnDiorComprar.setText("Comprar");
        btnDiorComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiorComprarActionPerformed(evt);
            }
        });

        btnJCarolinaComprar.setText("Comprar");
        btnJCarolinaComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJCarolinaComprarActionPerformed(evt);
            }
        });

        spiLacome.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        spiLacome.setToolTipText("");
        spiLacome.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                spiLacomeHierarchyChanged(evt);
            }
        });
        spiLacome.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spiLacomeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        spiLacome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spiLacomeMouseClicked(evt);
            }
        });

        spiDior.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        spiKenzo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        spiLavie.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        spiMilion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        spiCoco.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        spiJadore.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        spiDolce.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        spiLight.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        spiCarolina.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel1.setText("Quantidade disponível: 50");

        jLabel2.setText("Quantidade disponível: 50");

        jLabel3.setText("Quantidade disponível: 50");

        jLabel4.setText("Quantidade disponível: 50");

        jLabel5.setText("Quantidade disponível: 50");

        jLabel6.setText("Quantidade disponível: 50");

        jLabel7.setText("Quantidade disponível: 50");

        jLabel8.setText("Quantidade disponível: 50");

        jLabel9.setText("Quantidade disponível: 50");

        jLabel10.setText("Quantidade disponível: 50");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKenzo)
                    .addComponent(btnMilion)
                    .addComponent(btnLaVie)
                    .addComponent(btnCoco)
                    .addComponent(btnLacome)
                    .addComponent(btnJadore)
                    .addComponent(btnLight)
                    .addComponent(btnDolce)
                    .addComponent(btnCarolina)
                    .addComponent(btnDior))
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spiLacome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiDior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiKenzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiLavie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiMilion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiCoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiJadore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiDolce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiCarolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLacomeComprar)
                    .addComponent(btnMilionComprar)
                    .addComponent(btnKenzoComprar)
                    .addComponent(btnLavieComprar)
                    .addComponent(btnCocoComprar)
                    .addComponent(btnLightComprar)
                    .addComponent(btnJadoreComprar)
                    .addComponent(btnDolceComprar)
                    .addComponent(btnJCarolinaComprar)
                    .addComponent(btnDiorComprar))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLacome)
                    .addComponent(btnLacomeComprar)
                    .addComponent(spiLacome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMilion)
                    .addComponent(btnMilionComprar)
                    .addComponent(spiMilion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKenzo)
                    .addComponent(btnKenzoComprar)
                    .addComponent(spiKenzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaVie)
                    .addComponent(btnLavieComprar)
                    .addComponent(spiLavie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCoco)
                    .addComponent(btnCocoComprar)
                    .addComponent(spiCoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJadore)
                    .addComponent(btnJadoreComprar)
                    .addComponent(spiJadore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLight)
                    .addComponent(btnLightComprar)
                    .addComponent(spiLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDolce)
                    .addComponent(btnDolceComprar)
                    .addComponent(spiDolce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarolina)
                    .addComponent(btnJCarolinaComprar)
                    .addComponent(spiCarolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDior)
                    .addComponent(btnDiorComprar)
                    .addComponent(spiDior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        spiLacome.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLacomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLacomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLacomeActionPerformed

    private void btnDolceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDolceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDolceActionPerformed

    private void btnDiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiorActionPerformed

    private void btnMilionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMilionActionPerformed

    private void btnLacomeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_btnLacomeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLacomeComponentAdded

    private void btnLacomeComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLacomeComprarActionPerformed
        int value = spiLacome.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Esse produto só possui 50 unidades, escolha um valor menor que esse e faça sua reserva.");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnLacomeComprarActionPerformed

    private void spiLacomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spiLacomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spiLacomeMouseClicked

    private void spiLacomeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spiLacomeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_spiLacomeAncestorAdded

    private void spiLacomeHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_spiLacomeHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spiLacomeHierarchyChanged

    private void btnMilionComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilionComprarActionPerformed
                int value = spiMilion.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnMilionComprarActionPerformed

    private void btnKenzoComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKenzoComprarActionPerformed
                int value = spiKenzo.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnKenzoComprarActionPerformed

    private void btnLavieComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLavieComprarActionPerformed
        int value = spiLavie.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLavieComprarActionPerformed

    private void btnCocoComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocoComprarActionPerformed
        int value = spiCoco.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCocoComprarActionPerformed

    private void btnJadoreComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadoreComprarActionPerformed
        int value = spiJadore.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnJadoreComprarActionPerformed

    private void btnLightComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLightComprarActionPerformed
        int value = spiLight.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLightComprarActionPerformed

    private void btnDolceComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDolceComprarActionPerformed
        int value = spiDolce.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDolceComprarActionPerformed

    private void btnJCarolinaComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJCarolinaComprarActionPerformed
        int value = spiCarolina.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnJCarolinaComprarActionPerformed

    private void btnDiorComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiorComprarActionPerformed
        int value = spiDior.getValue().hashCode();
        
        if (value < 1){
            JOptionPane.showMessageDialog(null, "Escolha ao menos 1 unidade e faça sua reserva");
        }
        else{
            JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiorComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCarolina;
    private javax.swing.JToggleButton btnCoco;
    private javax.swing.JButton btnCocoComprar;
    private javax.swing.JToggleButton btnDior;
    private javax.swing.JButton btnDiorComprar;
    private javax.swing.JToggleButton btnDolce;
    private javax.swing.JButton btnDolceComprar;
    private javax.swing.JButton btnJCarolinaComprar;
    private javax.swing.JToggleButton btnJadore;
    private javax.swing.JButton btnJadoreComprar;
    private javax.swing.JToggleButton btnKenzo;
    private javax.swing.JButton btnKenzoComprar;
    private javax.swing.JToggleButton btnLaVie;
    private javax.swing.JToggleButton btnLacome;
    private javax.swing.JButton btnLacomeComprar;
    private javax.swing.JButton btnLavieComprar;
    private javax.swing.JToggleButton btnLight;
    private javax.swing.JButton btnLightComprar;
    private javax.swing.JToggleButton btnMilion;
    private javax.swing.JButton btnMilionComprar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spiCarolina;
    private javax.swing.JSpinner spiCoco;
    private javax.swing.JSpinner spiDior;
    private javax.swing.JSpinner spiDolce;
    private javax.swing.JSpinner spiJadore;
    private javax.swing.JSpinner spiKenzo;
    private javax.swing.JSpinner spiLacome;
    private javax.swing.JSpinner spiLavie;
    private javax.swing.JSpinner spiLight;
    private javax.swing.JSpinner spiMilion;
    // End of variables declaration//GEN-END:variables
}
